# Generated by Django 3.2.22 on 2024-07-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0013_auto_20240510_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "approved"),
                    ("I", "in_appeal"),
                    ("P", "pending"),
                    ("E", "pending_deletion"),
                    ("D", "deleted"),
                    ("S", "disabled"),
                    ("L", "locked"),
                    ("R", "rejected"),
                    ("U", "unsupported_language"),
                    ("T", "paused"),
                    ("L", "limit_exceeded"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
