# Generated by Django 3.2.22 on 2025-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0014_alter_templatetranslation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="body",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="footer",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="templatebutton",
            name="type",
            field=models.CharField(
                choices=[
                    ("QUICK_REPLY", "quick_reply"),
                    ("PHONE_NUMBER", "phone_number"),
                    ("URL", "url"),
                    ("COPY_CODE", "copy_code"),
                ],
                max_length=20,
            ),
        ),
    ]
