# Generated by Django 3.2.22 on 2026-06-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0015_auto_20250821_1729"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateLastDispatch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_uuid", models.UUIDField()),
                ("name", models.CharField(max_length=512)),
                ("meta_template_id", models.CharField(max_length=64)),
                ("last_fired_on", models.DateTimeField()),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_last_dispatches",
                        to="orgs.org",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_dispatches",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "unique_together": {("org", "meta_template_id")},
            },
        ),
    ]
