# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apks", "0004_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apk",
            name="apk_type",
            field=models.CharField(
                choices=[("R", "Relayer application APK"), ("M", "Message Pack application APK")], max_length=1
            ),
        ),
    ]
