# Generated by Django 3.2.18 on 2023-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0090_auto_20211209_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(
                default="infinity", help_text="What plan your organization is on", max_length=16, verbose_name="Plan"
            ),
        ),
    ]
