# Generated by Django 3.2.22 on 2024-04-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0091_org_brain_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="proj_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
