# Generated by Django 3.2.22 on 2025-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0092_org_proj_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(
                default="infinity", help_text="What plan your organization is on", max_length=16, verbose_name="Plan"
            ),
        ),
    ]
