# Generated by Django 3.2.25 on 2026-02-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0093_auto_20251212_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(
                default="infinity", help_text="What plan your organization is on", max_length=16, verbose_name="Plan"
            ),
        ),
        migrations.CreateModel(
            name="UniqueContactCount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_contact_counts",
                        to="orgs.org",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="uniquecontactcount",
            index=models.Index(fields=["day"], name="orgs_unique_day_9be449_idx"),
        ),
        migrations.AddIndex(
            model_name="uniquecontactcount",
            index=models.Index(fields=["org", "day"], name="orgs_unique_org_id_134c28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="uniquecontactcount",
            unique_together={("org", "day")},
        ),
    ]
