# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models
import django.db.models.deletion
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0094_unique_contact_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditalert',
            name='alert_type',
            field=models.CharField(choices=[('O', 'Credits over'), ('L', 'Low credits'), ('E', 'Credits expiring soon')], max_length=1),
        ),
        migrations.AlterField(
            model_name='debit',
            name='beneficiary',
            field=models.ForeignKey(help_text='Optional top-up that was allocated with these credits', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='orgs.topup'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='topup',
            field=models.ForeignKey(help_text='The top-up these credits are applied against', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='orgs.topup'),
        ),
        migrations.AlterField(
            model_name='org',
            name='brain_on',
            field=models.BooleanField(default=False, help_text='Whether this organization uses the router'),
        ),
        migrations.AlterField(
            model_name='org',
            name='config',
            field=temba.utils.models.JSONAsTextField(default=dict, help_text='Additional organization-specific configuration', null=True, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='org',
            name='date_format',
            field=models.CharField(choices=[('D', 'DD-MM-YYYY'), ('M', 'MM-DD-YYYY'), ('Y', 'YYYY-MM-DD')], default='D', help_text='Specify if the day or month comes first in dates', max_length=1, verbose_name='Date format'),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_anon',
            field=models.BooleanField(default=False, help_text='Specify if this organization anonymizes the phone numbers of contacts'),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Specify if this organization is currently flagged'),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_multi_org',
            field=models.BooleanField(default=False, help_text='Specify if this organization can have child workspaces'),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_multi_user',
            field=models.BooleanField(default=False, help_text='Specify if this organization can have multiple logins'),
        ),
        migrations.AlterField(
            model_name='org',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Specify if this organization is currently suspended'),
        ),
        migrations.AlterField(
            model_name='org',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('cs', 'Czech'), ('es', 'Spanish'), ('fr', 'French'), ('mn', 'Mongolian'), ('pt-br', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian')], default='en-us', help_text='The default website language for new users', max_length=64, null=True, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='org',
            name='plan',
            field=models.CharField(default='topups', help_text='The plan your organization is on', max_length=16, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='org',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': "This slug isn't available"}, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='org',
            name='stripe_customer',
            field=models.CharField(blank=True, help_text='The Stripe customer ID for your organization', max_length=32, null=True, verbose_name='Stripe customer'),
        ),
        migrations.AlterField(
            model_name='org',
            name='uses_topups',
            field=models.BooleanField(default=True, help_text='Specify if this organization uses top-ups'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='credits',
            field=models.IntegerField(help_text='The number of credits bought in this top-up', verbose_name='Number of credits'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='expires_on',
            field=models.DateTimeField(help_text='The date that this top up will expire', verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='price',
            field=models.IntegerField(blank=True, help_text='The price paid for the messages in this top-up (in cents)', null=True, verbose_name='Price paid'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='stripe_charge',
            field=models.CharField(blank=True, help_text='The Stripe charge ID for this charge', max_length=32, null=True, verbose_name='Stripe charge ID'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('cs', 'Czech'), ('es', 'Spanish'), ('fr', 'French'), ('mn', 'Mongolian'), ('pt-br', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian')], default='en-us', max_length=8),
        ),
    ]
