# Generated by Django 3.2.22 on 2025-11-25 19:16

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0041_alter_campaigns_eventfire_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.TranslatableField(max_length=1500, null=True),
        ),
    ]
