# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0041_alter_campaigns_eventfire_sequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignevent",
            options={"verbose_name": "Campaign event", "verbose_name_plural": "Campaign events"},
        ),
        migrations.AlterField(
            model_name="campaign",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.TranslatableField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
    ]
