# Generated by Django 3.2.22 on 2025-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0136_add_adress_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
