# Generated by Django 3.2.25 on 2026-09-10 20:44

import django_countries.fields

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0137_alter_channel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[("P", "Power"), ("D", "Disconnected"), ("S", "SMS")],
                help_text="The type of alert the channel is sending",
                max_length=1,
                verbose_name="Alert type",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="ended_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ended on"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="sync_event",
            field=models.ForeignKey(
                help_text="The sync event that caused this alert to be sent (if any)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alerts",
                to="channels.syncevent",
                verbose_name="Sync event",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="alert_email",
            field=models.EmailField(
                blank=True,
                help_text="Email alerts will be sent to this address if there are issues sending",
                max_length=254,
                null=True,
                verbose_name="Alert email",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="claim_code",
            field=models.CharField(
                blank=True,
                help_text="The token the user will use to claim this channel",
                max_length=16,
                null=True,
                unique=True,
                verbose_name="Claim code",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, help_text="Country this channel is for", max_length=2, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="last_seen",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The last time this channel contacted the server",
                verbose_name="Last seen",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="os",
            field=models.CharField(
                blank=True,
                help_text="The Android OS version this channel is running on",
                max_length=255,
                null=True,
                verbose_name="OS",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="tps",
            field=models.IntegerField(
                help_text="The maximum number of messages sent per second",
                null=True,
                verbose_name="Maximum transactions per second",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="error_reason",
            field=models.CharField(
                choices=[("P", "Provider"), ("B", "Busy"), ("N", "No answer"), ("M", "Answering machine")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("I", "In progress"),
                    ("D", "Complete"),
                    ("E", "Error"),
                    ("F", "Failed"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="channelcount",
            name="count_type",
            field=models.CharField(
                choices=[
                    ("IM", "Incoming message"),
                    ("OM", "Outgoing message"),
                    ("IV", "Incoming voice"),
                    ("OV", "Outgoing voice"),
                    ("LS", "Success log record"),
                    ("LE", "Error log record"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="channelevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown call type"),
                    ("mt_call", "Outgoing call"),
                    ("mt_miss", "Missed outgoing call"),
                    ("mo_call", "Incoming call"),
                    ("mo_miss", "Missed incoming call"),
                    ("stop_contact", "Stop contact"),
                    ("new_conversation", "New conversation"),
                    ("referral", "Referral"),
                    ("welcome_message", "Welcome message"),
                ],
                max_length=16,
            ),
        ),
    ]
