# Generated by Django 3.2.22 on 2024-05-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0163_alter_msg_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="template",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
