# Generated by Django 3.2.22 on 2024-11-12 14:56

from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0165_populate_template_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="broadcast_type",
            field=models.CharField(choices=[("D", "default"), ("W", "whatsapp")], default="D", max_length=1),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="base_language",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.TranslatableField(blank=True, max_length=640, null=True),
        ),
    ]
