# Generated by Django 3.2.22 on 2025-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0166_auto_20241112_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="is_bulk_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="template_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
