# Generated by Django 3.2.22 on 2025-08-20 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0092_org_proj_uuid"),
        ("msgs", "0167_auto_20250811_1748"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastStatistics",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("processed", models.IntegerField(default=0)),
                ("sent", models.IntegerField(default=0)),
                ("delivered", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("read", models.IntegerField(default=0)),
                ("contact_count", models.IntegerField(default=0)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("template_price", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ("currency", models.CharField(blank=True, max_length=20, null=True)),
                ("created_on", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="statistics", to="msgs.broadcast"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="broadcast_statistics", to="orgs.org"
                    ),
                ),
            ],
        ),
    ]
