# Generated by Django 3.2.22 on 2025-07-30 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0092_org_proj_uuid"),
        ("msgs", "0167_auto_20250730_2013"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastStatistics",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("processed", models.IntegerField(default=0)),
                ("sent", models.IntegerField(default=0)),
                ("delivered", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("contact_count", models.IntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="statistics", to="msgs.broadcast"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="broadcast_statistics", to="orgs.org"
                    ),
                ),
            ],
        ),
    ]
