# Generated by Django 3.2.25 on 2026-09-10 20:44

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0095_auto_20260910_2044"),
        ("msgs", "0173_guard_broadcast_statistics_sent_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportmessagestask",
            name="org",
            field=models.ForeignKey(
                help_text="The organization of the user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exportmessagestasks",
                to="orgs.org",
            ),
        ),
        migrations.AlterField(
            model_name="exportmessagestask",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
    ]
