# Generated by Django 3.2.22 on 2026-08-31 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0094_unique_contact_count"),
        ("contacts", "0143_auto_20210908_2224"),
        ("flows", "0264_alter_flowstart_contacts_sequence"),
        ("msgs", "0173_guard_broadcast_statistics_sent_delivered"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedTriggerGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "flow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_trigger_group",
                        to="flows.flow",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_trigger_group_link",
                        to="contacts.contactgroup",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_trigger_groups",
                        to="orgs.org",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="managedtriggergroup",
            index=models.Index(fields=["org"], name="msgs_mtg_org_idx"),
        ),
    ]
