# Generated by Django 3.2.25 on 2026-09-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0174_auto_20260910_2044'),
        ('msgs', '0174_managedtriggergroup'),
    ]

    operations = [
    ]
