# Generated by Django 3.2.25 on 2026-10-07

import django.db.models.deletion
import django.utils.timezone
import temba.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0145_consumer_identity"),
        ("orgs", "0095_auto_20260910_2044"),
        ("msgs", "0175_merge_20260910_2109"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("state", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=8)),
                ("opened_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_on", models.DateTimeField(null=True)),
                (
                    "close_reason",
                    models.CharField(
                        choices=[
                            ("ai_csat", "AI CSAT"),
                            ("ai_inactivity", "AI inactivity"),
                            ("human_inactivity", "Human inactivity"),
                            ("attendant", "Attendant"),
                            ("ticket_closed", "Ticket closed"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("idle_accumulated", models.IntegerField(default=0)),
                ("timer_deadline", models.DateTimeField(null=True)),
                (
                    "timer_kind",
                    models.CharField(choices=[("ai", "AI"), ("human", "Human")], max_length=8, null=True),
                ),
                ("timer_paused", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocols",
                        to="contacts.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="protocols", to="orgs.org"
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="msgs.protocol",
                    ),
                ),
                (
                    "urn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocols",
                        to="contacts.contacturn",
                    ),
                ),
            ],
            options={"db_table": "msgs_protocol"},
        ),
        migrations.AddField(
            model_name="msg",
            name="protocol",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msgs",
                to="msgs.protocol",
            ),
        ),
    ]
