# Generated by Django 3.2.22 on 2024-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0262_integrationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="is_mutable",
            field=models.BooleanField(default=True),
        ),
    ]
