# Generated by Django 3.2.25 on 2026-09-10 20:44

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0095_auto_20260910_2044"),
        ("flows", "0264_alter_flowstart_contacts_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportflowresultstask",
            name="org",
            field=models.ForeignKey(
                help_text="The organization of the user",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exportflowresultstasks",
                to="orgs.org",
            ),
        ),
        migrations.AlterField(
            model_name="exportflowresultstask",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="base_language",
            field=models.CharField(
                blank=True,
                default="base",
                help_text="The authoring language. Additional languages can be added later.",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="expires_after_minutes",
            field=models.IntegerField(
                default=10080, help_text="Minutes of inactivity that will cause expiration from this flow"
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="flow_type",
            field=models.CharField(
                choices=[("M", "Messaging"), ("V", "Phone call"), ("B", "Background"), ("S", "Surveyor")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="session_type",
            field=models.CharField(
                choices=[("M", "Messaging"), ("V", "Phone call"), ("B", "Background"), ("S", "Surveyor")],
                default="M",
                max_length=1,
            ),
        ),
    ]
