# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models
import django.db.models.deletion
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0095_auto_20260910_2044'),
        ('contacts', '0143_auto_20210908_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uuid',
            field=models.CharField(db_index=True, default=temba.utils.models.generate_uuid, help_text='The unique identifier for this object', max_length=36, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='value_type',
            field=models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('D', 'Date and time'), ('S', 'State'), ('I', 'District'), ('W', 'Ward')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='uuid',
            field=models.CharField(db_index=True, default=temba.utils.models.generate_uuid, help_text='The unique identifier for this object', max_length=36, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user', on_delete=django.db.models.deletion.PROTECT, related_name='exportcontactstasks', to='orgs.org'),
        ),
        migrations.AlterField(
            model_name='exportcontactstask',
            name='uuid',
            field=models.CharField(db_index=True, default=temba.utils.models.generate_uuid, help_text='The unique identifier for this object', max_length=36, unique=True, verbose_name='Unique identifier'),
        ),
    ]
