# Generated by Django 3.2.25 on 2026-10-07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0095_auto_20260910_2044"),
        ("contacts", "0144_auto_20260910_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacturn",
            name="attachment_status",
            field=models.CharField(
                choices=[
                    ("not-attached", "Not attached"),
                    ("claimed", "Claimed"),
                    ("confirmed", "Confirmed"),
                ],
                default="not-attached",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ContactAnchor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("commerce_user_id", "Commerce user id"),
                            ("verified_email", "Verified email"),
                            ("tax_document", "Tax document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("verified", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchors",
                        to="contacts.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_anchors",
                        to="orgs.org",
                    ),
                ),
            ],
            options={"db_table": "contacts_anchor"},
        ),
        migrations.AddConstraint(
            model_name="contactanchor",
            constraint=models.UniqueConstraint(
                fields=("org", "anchor_type", "value"), name="unique_contact_anchor_per_org"
            ),
        ),
        migrations.CreateModel(
            name="ContactIdentityEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("anchor_type", models.CharField(max_length=32, null=True)),
                ("affected_protocol_ids", temba.utils.models.JSONField(default=list)),
                ("attachment_status", models.CharField(max_length=16, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("attached", "Attached"),
                            ("claimed", "Claimed"),
                            ("detached", "Detached"),
                            ("conflict", "Conflict"),
                            ("deleted", "Deleted"),
                            ("noop", "No-op"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_events",
                        to="contacts.contact",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_events",
                        to="orgs.org",
                    ),
                ),
                (
                    "urn",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_events",
                        to="contacts.contacturn",
                    ),
                ),
            ],
            options={"db_table": "contacts_identityevent"},
        ),
    ]
