# Generated by Django 3.2.25 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0144_auto_20260910_2044"),
    ]

    operations = [
        migrations.RunSQL("SET LOCAL lock_timeout = '5s'", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name="contactgroup",
            name="is_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
