# Generated by Django 3.2.25 on 2026-09-24

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("contacts", "0145_contactgroup_is_opt_in"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name="contactgroup",
                    constraint=models.UniqueConstraint(
                        condition=Q(is_active=True, is_opt_in=True),
                        fields=("org",),
                        name="contacts_contactgroup_one_active_opt_in",
                    ),
                )
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS contacts_contactgroup_one_active_opt_in "
                        "ON contacts_contactgroup (org_id) WHERE is_opt_in AND is_active"
                    ),
                    reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS contacts_contactgroup_one_active_opt_in",
                )
            ],
        )
    ]
