# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='requires_consent',
            field=models.BooleanField(default=True, help_text='Is consent required?'),
        ),
    ]
