# Generated by Django 3.2.18 on 2023-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_logs", "0013_auto_20210928_1505"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                    ("whataspp_check_health", "WhatsApp Health Check"),
                    ("teams_tokens_synced", "Teams Tokens Synced"),
                ],
                max_length=32,
            ),
        ),
    ]
