# Generated by Django 3.2.17 on 2023-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_logs", "0014_alter_httplog_log_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                    ("whataspp_check_health", "WhatsApp Health Check"),
                    ("whatsapp_catalogs_synced", "WhatsApp Catalogs Synced"),
                    ("whatsapp_products_synced", "WhatsApp Products Synced"),
                    ("teams_tokens_synced", "Teams Tokens Synced"),
                ],
                max_length=32,
            ),
        ),
    ]
