# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0017_httplog_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents synced"),
                    ("classifier_called", "Classifier called"),
                    ("ticketer_called", "Ticketing service called"),
                    ("airtime_transferred", "Airtime transferred"),
                    ("whatsapp_templates_synced", "WhatsApp templates synced"),
                    ("whatsapp_tokens_synced", "WhatsApp tokens synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp contacts refreshed"),
                    ("whataspp_check_health", "WhatsApp health check"),
                    ("whatsapp_catalogs_synced", "WhatsApp catalogs synced"),
                    ("whatsapp_products_synced", "WhatsApp products synced"),
                    ("teams_tokens_synced", "Teams tokens synced"),
                ],
                max_length=32,
            ),
        ),
    ]
