# Generated by Django 3.2.22 on 2024-10-31 19:09

from django.db import migrations, models

import temba.utils.uuid


def copy_uuid_to_queue_uuid(apps, schema_editor):
    topic = apps.get_model("tickets", "Topic")

    for queue in topic.objects.all():
        queue.queue_uuid = queue.uuid
        queue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0025_remove_ticket_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="queue_uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4),
        ),
        migrations.RunPython(copy_uuid_to_queue_uuid),
    ]
