# Generated by Django 3.2.22 on 2025-07-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CTWA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ctwa_clid",
                    models.CharField(
                        db_index=True, help_text="Click to WhatsApp Click ID", max_length=255, unique=True
                    ),
                ),
                ("channel_uuid", models.UUIDField(db_index=True, help_text="Channel UUID")),
                ("waba", models.CharField(help_text="WhatsApp Business Account ID", max_length=255)),
                ("contact_urn", models.CharField(help_text="Contact URN", max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
