# Generated by Django on 2026-01-26

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):
    dependencies = [
        ("sql", "0003_bigint_m2ms"),
    ]

    operations = [InstallSQL("0004_fix_flowstartcount_fk")]
