# Generated by Django 3.2.17 on 2023-08-28 13:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0090_auto_20211209_2120"),
        ("channels", "0135_alter_channellog_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("facebook_catalog_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="catalogs", to="channels.channel"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="catalogs", to="orgs.org"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("facebook_product_id", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("product_retailer_id", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="wpp_products.catalog"
                    ),
                ),
            ],
        ),
    ]
