# Generated by Django 3.2.23 on 2024-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wpp_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="facebook_product_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_retailer_id",
            field=models.CharField(max_length=100),
        ),
    ]
