# Generated by Django 3.2.25 on 2026-09-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0138_auto_20260910_2044'),
        ('flows', '0265_auto_20260910_2044'),
        ('triggers', '0021_auto_20210625_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='channel',
            field=models.ForeignKey(help_text='The associated channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='channels.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='flow',
            field=models.ForeignKey(help_text='The flow that will be started', on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='flows.flow', verbose_name='Flow'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='keyword',
            field=models.CharField(blank=True, help_text='Word to match in the message text', max_length=16, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='match_type',
            field=models.CharField(choices=[('F', 'Message starts with the keyword'), ('O', 'Message contains only the keyword')], default='F', help_text='How to match a message with a keyword', max_length=1, null=True, verbose_name='Trigger when'),
        ),
    ]
